### ISSUE TITLE
Node Attributes Configuration is Missing in the provider

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#107]
To Enable Hot Warm Architecture in Elastic Cloud, node attributes are to be assigned to nodes so as ILM policy can be applied to perform the required actions on the indices as per the ILM policy.

Update in the Provider configuration is required to add this functionality.

Benefit of having this change will enable support for Hot Warm architecture.

**Comment by marclop** [comment]
@ggsood thanks for the Issue and the Pull Request, but we won't be adding the `node_attribute` map in the "ec_deployment" resource since the attributes are already set in the deployment template which after #98, we will use as the "blueprint" or "template" for a deployment. Hot / Warm `node_attributes` are already set in the template and the user won't be able to set it, just like the user won't be able to set the `node_type_<type>` anymore after that PR is merged.

It will reduce the verbose nature of the terraform definitions and prevent users from inputting wrong or unexacting `node_attributes` which would cause the deployment to become unhealthy.

**Comment by ggsood** [comment]
Thanks @marclop for the information, will close this issue now.
