### ISSUE TITLE
Elasticsearch user `config` is not discovered

### ISSUE THREAD

**Issue by wgebis** [elastic/terraform-provider-ec#214]
## Expected Behavior
According to docs, elasticsearch config section should be honoured and should be pushable to `ec_deployment`.

## Current Behavior
When `config` is defined under UI it is not handled by the TF resource. Kibana config section works as expected. 

## Possible Solution
Adding support for elasticsearch `config` handling. 

## Steps to Reproduce
1. Create elasticsearch `config` under Edit / User setting overwrites
2. Run terraform plan/apply
3. Changes are not detected. 

## Your Environment
* Version used: 0.1.0-beta
* ES version: 7.10.1

**Comment by zonArt** [comment]
Experimented the same issue. And to add some context, when trying to push a faulty configuration my deployment just failed meaning in a way it's aware it needs to change something but when wrong refuses to do it. Once I've corrected my config block, it tried to redeploy ES and succeeded, but when I looked to the config nothing changed. Now that I run terraform again it just tells me it's ok.

**Comment by Kushmaro** [comment]
Thanks @zonArt @wgebis , this is actually a known issue that occurs due to our API model having two config sections - one per elasticsearch topology element, and one per all elasticsearch component.

IIRC, it's something we're trying to resolve by having the UI present & migrate topology specific settings to the global elasticsearch settings, thus, everything will be displayed and behave correctly. 

I'll update when this is resolved on the Cloud UI front. For the terraform provider, we think the correct behaviour is having a single config section to apply to all elasticsearch elements.

Do feel free to elaborate on any use cases where you think this may not be the desired case.

**Comment by wgebis** [comment]
@Kushmaro Thanks.
I wonder, if I define the config for all elasticsearch component, every elasticsearch instance will have that config? If I push elasticsearch config via current ec provider, where I will be able to see it on the UI?

**Comment by Kushmaro** [comment]
@wgebis if you push a config using the provider, it goes to the "global" space which applies to all elasticsearch instances (/cc @marclop to keep me honest )

You will (currently) not be able to see it in the UI (but the config will be applied). That is the internal issue I've mentioned we're trying to resolve.

**Comment by wgebis** [comment]
@Kushmaro So I will handle it in that way currently. Look forward to able to view the config on UI as well. 
Thanks!
