### ISSUE TITLE
ec_deployment_traffic_filter: add data source

### ISSUE THREAD

**Issue by guitmz** [elastic/terraform-provider-ec#245]
## Overview
Implement a data resource which allows the user to search traffic filters, and retrieve a result to be used in other resources.

## Possible Implementation
Similar to https://github.com/elastic/terraform-provider-ec/issues/8 (https://github.com/elastic/terraform-provider-ec/pull/88) perhaps.

```hcl
data "ec_deployment_traffic_filter" "example" {
  name = "My traffic filter"
}
```

which should expose `ec_deployment_traffic_filter.example.id`, based on its name.

**Comment by marclop** [comment]
Thanks for opening the issue, I've moved into your backlog to tackle as best as we can.

**Comment by marclop** [comment]
I've had a chance to have a look at this and I'm afraid we won't be implementing any search by name since there can be multiple traffic filtering rules that share the same name.

If you'd like to reference a traffic filter by ID, you can do so by creating modules around the terraform provider and exposing the IDs of the traffic filters you'd like to share between them. Optionally, you could use a list or a map of traffic filters ID that are directly passed to terraform using variables.
