### ISSUE TITLE
Custom extensions removed after applying Terraform changes

### ISSUE THREAD

**Issue by shawn-orange** [elastic/terraform-provider-ec#277]
## Question
Not sure if this is a bug exactly, so posting as a question for now.

We’ve been working with the provider for a couple months now, and it’s going well, but we’re having one big issue that's a growing concern.
 
We have a custom extension that holds the synonym files required by one of our indices.  If the synonyms don’t exist, the index can’t be created.  If the index has already been created and then synonyms are removed, the index goes red.
 
The problem is we can’t specify the custom extension in the cluster’s terraform definition, or at least we haven’t found a way to do it yet.  Looking at the [ec_deployment documentation](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment), attaching plugins (and presumably extensions) is only available from the UI and ecctl.  
 
So far we’ve spun up our clusters through Terraform, then attached the custom extension to it manually through the ESS GUI.  The problem is that the next time we apply a change to that cluster through terraform it removes the custom extension.  That in turn breaks our index.  

We can recover by closing the index, attaching the custom extension through the UI manually, then opening the index, but we’d prefer to do updates, especially in ESS, without this downtime.  
 
The main questions are:
1. Is there a way to attach a custom extension to a cluster through Terraform?
2. If not, is there a way to tell terraform to ignore extensions on subsequent updates, and prevent the extension removal that we’re experiencing?

**Comment by marclop** [comment]
Thanks for opening an issue reporting this bug @shawn-orange,

The flow you describe is very much in place in the `v0.1.0-beta` version since we did not add support to handle user bundles or plugins and it's unfortunately causing the behavior you're seeing.

#264 has been merged and is available on master, which adds an `elasticsearch.extension` block to do exactly what you're looking for. A new version of the terraform provider (`v0.1.0`) will be released later this week.

**Comment by shawn-orange** [comment]
That's great news, thanks - we'll be watching for the new release!
