### ISSUE TITLE
Enable kibana sso though terraform provider

### ISSUE THREAD

**Issue by romankor** [elastic/terraform-provider-ec#319]
## Question
Is that possible to enable SSO through the terraform provider? 
Given that [post](https://www.julientanay.com/blog/2020-08-21-elastic-cloud-sso/), some things need's to be configured, one of the is a secret in the Keystore and the other one is actually putting the kibana endpoint URL into `elasticsearch.yaml` , and the kibana url is not really available when I am creating the ES cluster. 

Also I don't seem to find how to put a secret into the keystore with the provider.  Is that right ?

**Comment by marclop** [comment]
@romankor we currently do not support the current Elasticsearch Keystore integration. Since it's an Elasticsearch API and not with the Elastic Cloud APIs, which this provider aims to cover.

We currently do not have plans for an Elasticsearch Terraform provider, but I can pass along your +1 as an Enhancement Request.

**Comment by RobDTech** [comment]
An Elasticsearch Terraform provider would be brilliant! 
We currently have our ES Cloud infrastructure managed by Terraform and we've written a basic app to maintain our config of ES by sending API requests. It's not very elegant :)
