### ISSUE TITLE
Add users and roles as resources that can be managed via Terraform.

### ISSUE THREAD

**Issue by stuartMoorhouse** [elastic/terraform-provider-ec#375]
## Overview
I would like to be able to define Users and Roles as resources in the EC Terraform provider.

## Testing
An example scenario could be the User, Roles and permissions needed to install a Beat on a host are created via Terraform, and the installation can then be run on a host, using the Roles that were defined.

## Context
I am trying to create lab environments for testing: for example, an EC deployment and a linux host, that has Filebeat installed.

## Your Environment
I run my Terraform builds on an ad-hoc basis.

**Comment by marclop** [comment]
Hi @stuartMoorhouse,

Are you asking us to support users and roles resources that are backed by Elasticsearch? If so, that is out of the scope of the Terraform provider since the provider interacts exclusively with the [Elasticsearch Service (or Elastic Cloud) API](https://www.elastic.co/guide/en/cloud/current/ec-restful-api.html).

We're discussing and planning how to proceed with the development of an Elastic Stack provider that will interact with Elasticsearch and potentially other Elastic Stack component APIs. This feature would then fall into the scope of that provider.

I hope this helps clarify things.

**Comment by stuartMoorhouse** [comment]
Yes, that was what I was looking for.
