### ISSUE TITLE
acceptance: Tests fail with errors unrelated to TF provider

### ISSUE THREAD

**Issue by karencfv** [elastic/terraform-provider-ec#38]
## Description
Currently acceptance tests can sometimes fail when there are errors 
unrelated to the terraform provider.

For example, if a deployment is unhealthy (unassigned shard or whatever),
or the deployment failed to delete (which only issues a warning), etc, the tests will fail. 

It seems to me that it would probably make sense to either log these errors somehow,
or not take these errors into account at all as they can provide false positives.

**Comment by karencfv** [comment]
What do you think @marclop ?

**Comment by marclop** [comment]
It would make sense to log something, but the deployment gets destroyed at the end of the test which doesn't make for much of a debugging workflow.

I've only seen the error show up when "plan failed due to unknown error" appears in the plan tracker logs.
```
* deployment [d2d9afb696d4b79baa642739e142c14a] - [kibana][046e06f37d8d4c44908dc9ba1d3c1ef3]: caught error: "plan failed due to unknown error"
```

This comes from the SDK:

https://github.com/elastic/cloud-sdk-go/blob/master/pkg/plan/track_step.go#L78-L86

**Comment by karencfv** [comment]
The tests also seem to fail when the deployment is unhealthy 🤔 I'm not really sure we need to check deployment health?

There was also a time when the test reported a deployment had failed to destroy but when I went to check it had been a false positive. 

I think it could be a good idea to relax checks a bit? idk, what do you think?

**Comment by marclop** [comment]
I think it's probably OK to remove the `Healthy` check
