### ISSUE TITLE
Terraform apply fails with: Error: failed to obtain a stack version matching "7.14.2"

### ISSUE THREAD

**Issue by dkarnutsch** [elastic/terraform-provider-ec#416]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Terraform apply should work.

## Current Behavior

Terraform apply is failing with the following error (this was working fine for weeks now):
```
var.elastic_api_key
  API key to interact with elastic.co

  Enter a value: xxxxxxxxxxx==

╷
│ Error: failed to obtain a stack version matching "7.14.2": please specify a valid version_regex
│ 
│   with data.ec_stack.stack,
│   on elasticsearch.tf line 1, in data "ec_stack" "stack":
│    1: data "ec_stack" "stack" {
│ 
```
## Terraform definition

```tf
data "ec_stack" "stack" {
  version_regex = "7.14.2"
  region        = "azure-westeurope"
}

resource "ec_deployment" "elastic" {
  name = "${var.prefix}-elastic"

  region                 = "azure-westeurope"
  version                = data.ec_stack.stack.version
  deployment_template_id = "azure-memory-optimized-v2"

  elasticsearch {
    topology {
      id         = "hot_content"
      zone_count = 1 # no HA
      size       = "2g"
    }
  }

  kibana {}

  apm {
    topology {
      size = "0g" # disable apm
    }
  }

  enterprise_search {
    topology {
      size = "0g" # disable enterprise search
    }
  }
}
```
## Steps to Reproduce

1. terraform init
2. terraform apply

## Your Environment

* Version used: Provider: 0.3.0, Stack version: 7.14.2
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): go1.16.3 
* Server type and version: 
* Operating System and version: macOS 11.6 as well as CentOS 7 (CI/CD)
* Link to your project:

**Comment by et0x** [comment]
Also running into this issue after having used this version_regex for months.

**Comment by jketcham** [comment]
I'm guessing it's because elastic cloud only has a limited set of versions available to be used for provisioning, [from their docs](https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html#ec-version-policy-available):

> We make the two latest minor versions of the latest major version available for provisioning. In addition, the latest minor version of the previous major version is also available.

> Previous maintenance releases are removed as new ones becomes available. Only the latest maintenance release within an available minor version is available.

And (I believe) the ec_stack data provider will only return versions that are able to be used for provisioning. I was running into the same thing in the past. I really do wish they would keep more versions around for provisioning.

**Comment by dkarnutsch** [comment]
Thank you @jketcham, this was indeed the problem.

**Comment by donkeyx** [comment]
is there any movement on this issue, because this would block a simple scale operation and force a version upgrade.

**Comment by aalonso-solusoft** [comment]
I don't know why this issue is marked as closed. Now we have an active deployment of elastic stack with terraform on version 7.16.3 working but we can't update any other resources because the elastic stack provider fails with the message "failed to obtain a stack version matching 7.16.3". We have to update the elastic stack version to "7.17.1" for this to work.

This behaviour make sense for new deployments of elastic stack but no for already deployed elastic resources because using the manual aproach (creating the deployment with elastic cloud portal) we can maintain older elastic versions when new versions are released.
