### ISSUE TITLE
More available cluster versions

### ISSUE THREAD

**Issue by 4dminasecuretti** [elastic/terraform-provider-ec#437]
## Overview
It would be useful to be able to setup a elastic cluster via terraform in older versions.
Currently there are only 4 possibilities for the version: "latest", the two latest minor versions of the current major version and the latest minor version of the previous major version.
Otherwise you get an error: 
`Error: failed to obtain a stack version matching "7.13.3": please specify a valid version_regex
 with module.components.data.ec_stack.latest,
 on components/cluster.tf line 2, in data "ec_stack" "latest":
 2: data "ec_stack" "latest" {`

## Possible Implementation
Enabling of the latest stable minor versions of the last 3-4 major versions, too.
`data "ec_stack" "latest" {
  version_regex = "7.13.3"
  region        = "..."
}`

## Testing
Just Terraforming ;)

## Context
Sometimes it is necessary to test a feature in a test cluster without touching the productive one.
If the productive one runs on an older version than supported in terraform no real testing is possible.

## Your Environment
We are currently running a cluster in version 7.13.3 and can't setup an aquivalent one to test the upgrade for example.

**Comment by tobio** [comment]
@4dminasecuretti the versions available to the `ec_stack` datasource are the same as those presented in the Cloud UI and are covered by the [version policy](https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html#ec-version-policy-available).

It's possible to get older versions enabled on your account, which would then be available to the Terraform provider. Get in touch via the support portal or support@elastic.co with the version(s) you need available and we can get those enabled. 

I'm closing this issue out since it's not a limitation of the Terraform provider.
