### ISSUE TITLE
Elasticsearch instance type is carried over to the kibana and enterprise_search instance types and throws error.  

### ISSUE THREAD

**Issue by hp0620** [elastic/terraform-provider-ec#519]
## Question
I am reporting this behavior on behalf of another user. I was not able to reproduce this issue, but the user is experiencing an unexpected behavior using the provider. 

Using ec provider version 0.2.1 

The configuration used is: 
```
resource "ec_deployment" "azure-elastic" {
name = "azure-elastic"

# Mandatory fields
region = azure-centralus
version = "7.17.5"
deployment_template_id = "azure-compute-optimized-v2"

elasticsearch {
topology {
id = "hot_content"
size = "30g"
zone_count = 2
}
}

kibana {}

enterprise_search {}
}
```
And this user is getting 

```
Error: invalid configuration: 2 errors occurred: * enterprise_search topology: invalid instance_configuration_id: "azure.enterprisesearch.fsv2" doesn't match any of the deployment template instance configurations * kibana topology: invalid instance_configuration_id: "azure.kibana.fsv2" doesn't match any of the deployment template instance configurations
```
Just in case any incorrect previous setting persists, the user deleted the state, and recreated by running `init` and `plan` command before applying the config, but still failed. 

As I was not able to reproduce this issue, using the same configuration, I am reaching out here to see if there's anything missing in troubleshooting this issue. 

The error seems to be pointing to a case where the instance type picked up from the elasticsearch node is enforced to be applied for kibana and enterprise search instances as well, which are not available. 

I am not sure why the high cpu nodes are selected for the kibana and enterprise instance. Is there anything that I am missing? 

Thanks for taking a look.

**Comment by hp0620** [comment]
Updating the TF version, ec provider version, deleting the state, running init, and running plan and apply again resolved the issue for the user. 
Closing the ticket. Thanks.

**Comment by MattRyder** [comment]
I've just hit this, while altering the hardware profile for the deployment.

`* kibana topology: invalid instance_configuration_id: "azure.kibana.e32sv3" doesn't match any of the deployment template instance configurations`

Instead of removing everything, the solution was to manually provide the `instance_configuration_id` of the updated kibana instance. That should allow you to apply the change to the hardware profile.

It was a little difficult to find which configuration would be best, so I used the [create deployment page](https://cloud.elastic.co/deployments/create)'s "Equivalent API request" to take a look at what Elastic recommended for the new hardware profile. 

```tf
resource "ec_deployment" "funkyelasticsearch" {
  [...]

  kibana {
    topology {
      [...]
      instance_configuration_id = "azure.kibana.fsv2" 
    }
  }
}

```

**Comment by tobio** [comment]
This process is improved in the next version of the provider with https://github.com/elastic/terraform-provider-ec/pull/547.
